project:
  type: website
  output-dir: "../docs"
  title: "Unlocking Financial Insights: A Guide to SEC Data Analysis with R"

website:
  title: "Unlocking Financial Insights: A Guide to SEC Data Analysis with R"
  navbar: 
    tools:
    - icon: github
      menu:
      - text: Source code
        url: https://github.com/gp1981/SEC_data_analysis
  sidebar: 
    style: "docked"
    search: true
    contents: 
      - section: "**Basics**"
        contents: 
          - index.qmd
          - 01_data_retrieval.qmd
          - 02_data_exploration.qmd
          - 03_data_analysis.qmd
          - 04_data_visualization.qmd
          - 05_advanced_topics.qmd
      - section: "**Fundamental Analysis**"
        contents: 
          - 11_AAPL.qmd
      - section: "**Appendix A - R script and functions**"
        contents: 
          - A1_main_script.qmd
          - A2_Functions.qmd

    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


